export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT = "USER_LOGOUT";

export const CHANGE_ACTIVE_BOARD_PENDING = "CHANGE_ACTIVE_BOARD_PENDING";
export const CHANGE_ACTIVE_BOARD_SUCCESS = "CHANGE_ACTIVE_BOARD_SUCCESS";
export const CHANGE_ACTIVE_BOARD_FAILURE = "CHANGE_ACTIVE_BOARD_FAILURE";

export const FETCH_BOARDS_PENDING = "FETCH_BOARDS_PENDING";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE";

export const FETCH_BOARDINFO_PENDING = "FETCH_BOARDINFO_PENDING";
export const FETCH_BOARDINFO_SUCCESS = "FETCH_BOARDINFO_SUCCESS";
export const FETCH_BOARDINFO_FAILURE = "FETCH_BOARDINFO_FAILURE";

export const FETCH_TASKLIST_PENDING = "FETCH_TASKLIST_PENDING";
export const FETCH_TASKLIST_SUCCESS = "FETCH_TASKLIST_SUCCESS";
export const FETCH_TASKLIST_FAILURE = "FETCH_TASKLIST_FAILURE";

export const CREATE_TASKLIST_PENDING = "CREATE_TASKLIST_PENDING";
export const CREATE_TASKLIST_SUCCESS = "CREATE_TASKLIST_SUCCESS";
export const CREATE_TASKLIST_FAILURE = "CREATE_TASKLIST_FAILURE";

export const FETCH_TASKINFO_PENDING = "FETCH_TASKINFO_PENDING";
export const FETCH_TASKINFO_SUCCESS = "FETCH_TASKINFO_SUCCESS";
export const FETCH_TASKINFO_FAILURE = "FETCH_TASKINFO_FAILURE";

export const NEW_TASK_PENDING = "NEW_TASK_PENDING";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";
export const NEW_TASK_FAILURE = "NEW_TASK_FAILURE";

export const SWAP_TASK_CARD = "SWAP_TASK_CARD";

export const SWAP_LIST_CARD_PENDING = "SWAP_LIST_CARD_PENDING";
export const SWAP_LIST_CARD_FAILURE = "SWAP_LIST_CARD_FAILURE";
export const SWAP_LIST_CARD_SUCCESS = "SWAP_LIST_CARD_SUCCESS";

export const FETCH_ORGANIZATION_INFO_SUCCESS = "FETCH_ORGANIZATION_INFO_SUCCESS";
export const FETCH_ORGANIZATION_INFO_PENDING = "FETCH_ORGANIZATION_INFO_PENDING";
export const FETCH_ORGANIZATION_INFO_FAILURE = "FETCH_ORGANIZATION_INFO_FAILURE";

export const CREATE_BOARD_PENDING = "CREATE_BOARD_PENDING";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAILURE = "CREATE_BOARD_FAILURE";